root: true
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2017
extends:
  - airbnb
  - prettier
  - prettier/react
  - plugin:jest/recommended
plugins:
  - prettier
  - jest
rules:
  consistent-return: 0
  no-console: 0
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  react/jsx-filename-extension: 0
